In [1]:
import pandas as pd
import pickle
from string import ascii_uppercase as alphabet

In [2]:
# extracting all tables in website
all_tables = pd.read_html('data/2022fifa.html')

In [3]:
count =0 
for tables in all_tables:
    print('count>>>>>>>>',count)
    count+=1
    print(tables)
print(len(all_tables))

count>>>>>>>> 0
    0                                                  1
0 NaN  This article documents a current FIFA World Cu...
count>>>>>>>> 1
   كأس العالم لكرة القدم 2022Kaʾs al-ʿālam li-kurat al-qadam 2022  \
0                  الآن هو كل شيء (Now Is Everything)
1                                  Tournament details
2                                        Host country
3                                               Dates
4                                               Teams
5                                            Venue(s)
6                               Tournament statistics
7                                      Matches played
8                                        Goals scored
9                                          Attendance
10                                      Top scorer(s)
11  ← 2018 2026 → All statistics correct as of 24 ...

   كأس العالم لكرة القدم 2022Kaʾs al-ʿālam li-kurat al-qadam 2022.1
0                  الآن هو كل شيء (Now Is Everything)
1                                  Tournament details
2                                               Qatar
3                           20 November – 18 December
4                          32 (from 5 confederations)
5                                8 (in 5 host cities)
6                               Tournament statistics
7                                                  16
8                                 41 (2.56 per match)
9                          803,003 (50,188 per match)
10  Richarlison Enner Valencia Bukayo Saka Olivier...
11  ← 2018 2026 → All statistics correct as of 24 ...
count>>>>>>>> 2
                            Place Amount ($ million)
                            Place           Per team Total
0                       Champions                 42    42
1                      Runners-up                 30    30
2                     Third place                 27    27
3                    Fourth place                 25    25
4  5th–8th place (quarter-finals)                 17    68
5    9th–16th place (Round of 16)                 13   104
6   17th–32nd place (Group stage)                  9   144
7                           Total              Total   440
count>>>>>>>> 3
         Bidders   Votes
         Bidders Round 1     Round 2     Round 3     Round 4
0          Qatar      11          10          11          14
1  United States       3           5           6           8
2    South Korea       4           5           5  Eliminated
3          Japan       3           2  Eliminated  Eliminated
4      Australia       1  Eliminated  Eliminated  Eliminated
count>>>>>>>> 4
                                                   0  \
0  AFC (6)  Australia (38)  Iran (20)  Japan (24)...

                                                   1  \
0  CONCACAF (4)  Canada (41)  Costa Rica (31)  Me...

                                                   2  \
0  UEFA (13)  Belgium (2)  Croatia (12)  Denmark ...

                                                   3
0  .mw-parser-output .legend{page-break-inside:av...
count>>>>>>>> 5
                                               Pot 1  \
0  Qatar (51) (hosts)  Brazil (1)  Belgium (2)  F...

                                               Pot 2  \
0  Mexico (9)  Netherlands (10)  Denmark (11)  Ge...

                                               Pot 3  \
0  Senegal (20)  Iran (21)  Japan (23)  Morocco (...

                                               Pot 4
0  Cameroon (37)  Canada (38)  Ecuador (46)  Saud...
count>>>>>>>> 6
                                                     0  \
0    Referees Confederation Referee AFC Abdulrahman...
1                                             Referees
2                                        Confederation
3                                                  AFC
4                                                  AFC
..                                                 ...
131                                               UEFA
132                                               UEFA
133                                               UEFA
134                                               UEFA
135                                               UEFA

                                                     1  \
0    Assistant referees Confederation Assistant ref...
1                                             Referees
2                                              Referee
3                        Abdulrahman Al-Jassim (Qatar)
4                              Chris Beath (Australia)
..                                                 ...
131                        Tomasz Kwiatkowski (Poland)
132                      Juan Martínez Munuera (Spain)
133                             Benoît Millot (France)
134                               Paolo Valeri (Italy)
135                       Pol van Boekel (Netherlands)

                                                     2
0    Video assistant referees Confederation Video a...
1                                                  NaN
2                                                  NaN
3                                                  NaN
4                                                  NaN
..                                                 ...
131                                                NaN
132                                                NaN
133                                                NaN
134                                                NaN
135                                                NaN

[136 rows x 3 columns]
count>>>>>>>> 7
        Referees
   Confederation                                            Referee
0            AFC                      Abdulrahman Al-Jassim (Qatar)
1            AFC                            Chris Beath (Australia)
2            AFC                             Alireza Faghani (Iran)
3            AFC                                    Ma Ning (China)
4            AFC  Mohammed Abdulla Hassan Mohamed (United Arab E...
5            AFC                          Yoshimi Yamashita (Japan)
6            CAF                            Bakary Gassama (Gambia)
7            CAF                         Mustapha Ghorbal (Algeria)
8            CAF                        Victor Gomes (South Africa)
9            CAF                         Salima Mukansanga (Rwanda)
10           CAF                          Maguette Ndiaye (Senegal)
11           CAF                             Janny Sikazwe (Zambia)
12      CONCACAF                          Iván Barton (El Salvador)
13      CONCACAF                      Ismail Elfath (United States)
14      CONCACAF                          Mario Escobar (Guatemala)
15      CONCACAF                           Saíd Martínez (Honduras)
16      CONCACAF                               César Ramos (Mexico)
17      CONMEBOL                             Raphael Claus (Brazil)
18      CONMEBOL                           Andrés Matonte (Uruguay)
19      CONMEBOL                                Kevin Ortega (Peru)
20      CONMEBOL                     Fernando Rapallini (Argentina)
21      CONMEBOL                            Wilton Sampaio (Brazil)
22      CONMEBOL                          Facundo Tello (Argentina)
23      CONMEBOL                       Jesús Valenzuela (Venezuela)
24           OFC                       Matthew Conger (New Zealand)
25          UEFA                        Stéphanie Frappart (France)
26          UEFA                            István Kovács (Romania)
27          UEFA                       Danny Makkelie (Netherlands)
28          UEFA                          Szymon Marciniak (Poland)
29          UEFA                        Antonio Mateu Lahoz (Spain)
30          UEFA                           Michael Oliver (England)
31          UEFA                             Daniele Orsato (Italy)
32          UEFA                           Daniel Siebert (Germany)
33          UEFA                           Anthony Taylor (England)
34          UEFA                            Clément Turpin (France)
35          UEFA                           Slavko Vinčić (Slovenia)
count>>>>>>>> 8
   Assistant referees
        Confederation                          Assistant referee
0                 AFC              Mohammadreza Abolfazli (Iran)
1                 AFC                     Taleb Al-Marri (Qatar)
2                 AFC  Mohamed Al-Hammadi (United Arab Emirates)
3                 AFC      Hasan Al-Mahri (United Arab Emirates)
4                 AFC                    Saud Al-Maqaleh (Qatar)
..                ...                                        ...
64               UEFA                 Vasile Marinescu (Romania)
65               UEFA                        Adam Nunn (England)
66               UEFA                       Jan Seidel (Germany)
67               UEFA                  Paweł Sokolnicki (Poland)
68               UEFA             Hessel Steegstra (Netherlands)

[69 rows x 2 columns]
count>>>>>>>> 9
   Video assistant referees
              Confederation                Video assistant referee
0                       AFC               Abdulla Al-Marri (Qatar)
1                       AFC              Muhammad Taqi (Singapore)
2                       AFC                Shaun Evans (Australia)
3                       CAF               Rédouane Jiyed (Morocco)
4                       CAF                  Adil Zourak (Morocco)
5                  CONCACAF                  Drew Fischer (Canada)
6                  CONCACAF             Fernando Guerrero (Mexico)
7                  CONCACAF     Armando Villarreal (United States)
8                  CONMEBOL                 Julio Bascuñán (Chile)
9                  CONMEBOL               Nicolás Gallo (Colombia)
10                 CONMEBOL              Leodán González (Uruguay)
11                 CONMEBOL                  Juan Soto (Venezuela)
12                 CONMEBOL             Mauro Vigliano (Argentina)
13                     UEFA                Jérôme Brisard (France)
14                     UEFA              Bastian Dankert (Germany)
15                     UEFA   Ricardo de Burgos Bengoetxea (Spain)
16                     UEFA                  Marco Fritz (Germany)
17                     UEFA  Alejandro Hernández Hernández (Spain)
18                     UEFA            Massimiliano Irrati (Italy)
19                     UEFA            Tomasz Kwiatkowski (Poland)
20                     UEFA          Juan Martínez Munuera (Spain)
21                     UEFA                 Benoît Millot (France)
22                     UEFA                   Paolo Valeri (Italy)
23                     UEFA           Pol van Boekel (Netherlands)
count>>>>>>>> 10
                                              Lusail  \
0                              Lusail Iconic Stadium
1                         Capacity: 88,966[114][115]
2                                                NaN
3  Host cities in Qatar.mw-parser-output .locmap ...
4                                          Al Rayyan
5                      Khalifa International Stadium
6                         Capacity: 45,857[122][123]
7                                                NaN

                                             Al Khor  \
0                                    Al Bayt Stadium
1                         Capacity: 68,895[116][117]
2                                                NaN
3  Host cities in Qatar.mw-parser-output .locmap ...
4                                          Al Rayyan
5       Ahmad bin Ali Stadium[F] (Al Rayyan Stadium)
6                         Capacity: 45,032[124][125]
7                                                NaN

                                                Doha  \
0                                 Al Thumama Stadium
1                         Capacity: 44,400[118][119]
2                                                NaN
3  Stadiums in Doha areaEducation974KhalifaAl Thu...
4                                          Al Rayyan
5                             Education City Stadium
6                         Capacity: 44,667[126][127]
7                                                NaN

                                              Doha.1
0                                        Stadium 974
1                         Capacity: 44,089[120][121]
2                                                NaN
3  Stadiums in Doha areaEducation974KhalifaAl Thu...
4                                          Al Wakrah
5                                  Al Janoub Stadium
6                         Capacity: 44,325[128][129]
7                                                NaN
count>>>>>>>> 11
            Teams                                             Hotels  \
0       Argentina                          Qatar University Hostel 1
1       Australia           New Aspire Academy Athlete Accommodation
2         Belgium               Hilton Salwa Beach Resort and Villas
3          Brazil                      The Westin Doha Hotel and Spa
4        Cameroon            Banyan Tree Doha At La Cigale Mushaireb
5          Canada                        Century Marina Hotel Lusail
6      Costa Rica                                 dusitD2 Salwa Doha
7         Croatia                                        Hilton Doha
8         Denmark                           Retaj Salwa Resort & SPA
9         Ecuador                            Hyatt Regency Oryx Doha
10        England                Souq Al Wakra Hotel Qatar by Tivoli
11         France  Al Messila – A Luxury Collection Resort & Spa,...
12        Germany                              Zulal Wellness Resort
13          Ghana                DoubleTree by Hilton Doha – Al Sadd
14           Iran    Al Rayyan Hotel Doha Curio Collection by Hilton
15          Japan                            Radisson Blu Hotel Doha
16         Mexico                          Simaisma, A Murwab Resort
17        Morocco                              Wyndham Doha West Bay
18    Netherlands                                 The St. Regis Doha
19         Poland                                 Ezdan Palace Hotel
20       Portugal              Al Samriya Autograph Collection Hotel
21          Qatar                         Al Aziziyah Boutique Hotel
22   Saudi Arabia                     Sealine Beach, a Murwab Resort
23        Senegal                        Duhail Handball Sports Hall
24         Serbia                              Rixos Gulf Hotel Doha
25    South Korea                       Le Méridien City Center Doha
26          Spain                          Qatar University Hostel 2
27    Switzerland                            Le Royal Méridien, Doha
28        Tunisia                  Wyndham Grand Doha West Bay Beach
29  United States            Marsa Malaz Kempinski, The Pearl – Doha
30        Uruguay                              Pullman Doha West Bay
31          Wales                      Delta Hotels City Center Doha

                                       Training sites
0                    Qatar University Training Site 3
1                   Aspire Zone Training Facilities 5
2                                 Salwa Training Site
3                                 Al Arabi SC Stadium
4                               Al Sailiya SC Stadium
5                    Umm Salal SC Training Facilities
6                                  Al Ahli SC Stadium
7                            Al Ersal Training Site 3
8                                     Al Sailiya SC 2
9                    Mesaimeer SC Training Facilities
10                               Al Wakrah SC Stadium
11                                 Al Sadd SC Stadium
12                               Al Shamal SC Stadium
13                  Aspire Zone Training Facilities 1
14                 Al Rayyan SC Training Facilities 1
15               Al Sadd SC New Training Facilities 1
16                                 Al Khor SC Stadium
17                               Al Duhail SC Stadium
18                   Qatar University Training Site 6
19              Al Kharaitiyat SC Training Facilities
20                Al Shahaniya SC Training Facilities
21                  Aspire Zone Training Facilities 3
22                              Sealine Training Site
23                                     Al Duhail SC 2
24                    Al Arabi SC Training Facilities
25                            Al Egla Training Site 5
26                   Qatar University Training Site 1
27  University of Doha for Science and Technology ...
28                           Al Egla Training Sites 3
29                              Al Gharafa SC Stadium
30                           Al Ersal Training Site 1
31               Al Sadd SC New Training Facilities 2
count>>>>>>>> 12
                Tie-breaking criteria for group play
0  The ranking of teams in the group stage is det...
count>>>>>>>> 13
   Pos  \
0    1
1    2
2    3
3    4

  Team.mw-parser-output .navbar{display:inline;font-size:88%;font-weight:normal}.mw-parser-output .navbar-collapse{float:left;text-align:left}.mw-parser-output .navbar-boxtext{word-spacing:0}.mw-parser-output .navbar ul{display:inline-block;white-space:nowrap;line-height:inherit}.mw-parser-output .navbar-brackets::before{margin-right:-0.125em;content:"[ "}.mw-parser-output .navbar-brackets::after{margin-left:-0.125em;content:" ]"}.mw-parser-output .navbar li{word-spacing:-0.125em}.mw-parser-output .navbar a>span,.mw-parser-output .navbar a>abbr{text-decoration:inherit}.mw-parser-output .navbar-mini abbr{font-variant:small-caps;border-bottom:none;text-decoration:none;cursor:inherit}.mw-parser-output .navbar-ct-full{font-size:114%;margin:0 7em}.mw-parser-output .navbar-ct-mini{font-size:114%;margin:0 4em}vte  \
0                                        Netherlands
1                                            Ecuador
2                                            Senegal
3                                          Qatar (H)

   Pld  W  D  L  GF  GA  GD   Pts              Qualification
0    1  1  0  0   2   0  +2  3[a]  Advance to knockout stage
1    1  1  0  0   2   0  +2  3[a]  Advance to knockout stage
2    1  0  0  1   0   2  −2  0[b]                        NaN
3    1  0  0  1   0   2  −2  0[b]                        NaN
count>>>>>>>> 14
   Qatar     0–2                                            Ecuador
0    NaN  Report  Valencia .mw-parser-output .fb-goal>span{font-...
count>>>>>>>> 15
   Senegal     0–2               Netherlands
0      NaN  Report  Gakpo 84' Klaassen 90+9'
count>>>>>>>> 16
   Qatar Match 18  Senegal
0    NaN   Report      NaN
count>>>>>>>> 17
   Netherlands Match 19  Ecuador
0          NaN   Report      NaN
count>>>>>>>> 18
   Ecuador Match 35  Senegal
0      NaN   Report      NaN
count>>>>>>>> 19
   Netherlands Match 36  Qatar
0          NaN   Report    NaN
count>>>>>>>> 20
   Pos        Teamvte  Pld  W  D  L  GF  GA  GD   Pts  \
0    1        England    1  1  0  0   6   2  +4     3
1    2          Wales    1  0  1  0   1   1   0  1[a]
2    3  United States    1  0  1  0   1   1   0  1[a]
3    4           Iran    1  0  0  1   2   6  −4     0

               Qualification
0  Advance to knockout stage
1  Advance to knockout stage
2                        NaN
3                        NaN
count>>>>>>>> 21
                                             England     6–2  \
0  Bellingham 35' Saka 43', 62' Sterling 45+1' Ra...  Report

                        Iran
0  Taremi 65', 90+13' (pen.)
count>>>>>>>> 22
  United States     1–1            Wales
0      Weah 36'  Report  Bale 82' (pen.)
count>>>>>>>> 23
   Wales Match 17  Iran
0    NaN   Report   NaN
count>>>>>>>> 24
   England Match 20  United States
0      NaN   Report            NaN
count>>>>>>>> 25
   Wales Match 33  England
0    NaN   Report      NaN
count>>>>>>>> 26
   Iran Match 34  United States
0   NaN   Report            NaN
count>>>>>>>> 27
   Pos       Teamvte  Pld  W  D  L  GF  GA  GD   Pts  \
0    1  Saudi Arabia    1  1  0  0   2   1  +1     3
1    2        Poland    1  0  1  0   0   0   0  1[a]

In [4]:
# finding tables in group stage
all_tables[20]

,Pos,Teamvte,Pld,W,D,L,GF,GA,GD,Pts,Qualification
0,1,England,1,1,0,0,6,2,+4,3,Advance to knockout stage
1,2,Wales,1,0,1,0,1,1,0,1[a],Advance to knockout stage
2,3,United States,1,0,1,0,1,1,0,1[a],NaN
3,4,Iran,1,0,0,1,2,6,−4,0,NaN

In [5]:
# A -> H
# 11 -> 7*8 + 11 = 67
all_tables = pd.read_html('data/2022fifa.html')
for i in range(13,69,7): # 11 18 25
    print(i)
    df = all_tables[i]
    df.rename(columns={df.columns[1]:'Team'}, inplace=True)
    df.pop('Qualification')
#     print(df)

13
20
27
34
41
48
55
62

In [6]:
print(alphabet)

ABCDEFGHIJKLMNOPQRSTUVWXYZ

In [7]:
all_tables = pd.read_html('data/2022fifa.html')

dict_table = {}
for letter, i in zip(alphabet, range(13,69,7)): # A=11, B=18, ...
    df = all_tables[i]
    df.rename(columns={df.columns[1]:'Team'}, inplace=True)
    df.pop('Qualification')
    dict_table[f'Group {letter}'] = df

In [8]:
dict_table.keys()

dict_keys(['Group A', 'Group B', 'Group C', 'Group D', 'Group E', 'Group F', 'Group G', 'Group H'])

In [12]:
dict_table['Group H']

   Pos         Team  Pld  W  D  L  GF  GA  GD   Pts
0    1     Portugal    1  1  0  0   3   2  +1     3
1    2  South Korea    1  0  1  0   0   0   0  1[a]
2    2      Uruguay    1  0  1  0   0   0   0  1[a]
3    4        Ghana    1  0  0  1   2   3  −1     0

In [13]:
# Upload (..verify if uploaded correctly)
with open('data/dict_table', 'wb') as output:
    pickle.dump(dict_table, output)